---
- name: Install Autobox components
  hosts: localhost
  tasks:
    - name: Add Docker repo
      ansible.builtin.yum_repository:
          name: Docker
          description: Docker CE
          baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install necessary components via DNF (package manager)
      ansible.builtin.dnf:
        name:
          # - yum-utils
          # - vim
          # - nano
          - docker-ce
    # - name: Install necessary items via pip3
    #   ansible.builtin.pip:
    #     name: ansible-lint
    